WIDTH = 600
HEIGHT = 600
SCREEN_TITLE = "Battleship"
FPS = 60
MOVEMENT_SPEED = 5
SPRITE_SCALING = 0.5
OFFSCREEN_SPACE = 300

LEFT_LIMIT = -OFFSCREEN_SPACE
RIGHT_LIMIT = WIDTH + OFFSCREEN_SPACE
BOTTOM_LIMIT = -OFFSCREEN_SPACE
TOP_LIMIT = HEIGHT + OFFSCREEN_SPACE