MOVEMENT_SPEED = 3.5
OFFSCREEN_SPACE = 300
SPRITE_SCALING = 0.5
SPRITE_SCALING_LASER = 0.8
BULLET_SPEED = 5
SCREEN_HEIGHT = 800
SCREEN_WIDTH =  1500
SCREEN_TITLE = "Battleship"
FPS = 60

LEFT_LIMIT = -OFFSCREEN_SPACE
RIGHT_LIMIT = SCREEN_WIDTH + OFFSCREEN_SPACE
BOTTOM_LIMIT = -OFFSCREEN_SPACE
TOP_LIMIT = SCREEN_HEIGHT + OFFSCREEN_SPACE